### ISSUE TITLE
Import?

### ISSUE THREAD

**Issue by KaroBee** [tpe-lecture/group-03#1]
Hi,
hab gerade versucht, euer Repository in Eclipse zu Importen. Verstehe die Struktur nicht ganz und kann es auch nicht einfach als JUnit Test ausführen. Müsste es aufwändig in ein anderes Projekt kopieren.
Könnt ihr es entweder so hinterlegen, dass man es nur importieren muss und es funktioniert, oder eine ausführliche Readme schreiben, in der ihr Beschreibt, wie man es einbindet, damit es läuft?
Könnt mich auch gerne fragen, wie die erste Variante geht, wenn ihr nicht weiterkommt.

Und mir ist aufgefallen, dass ihr innerhalb der Instanz mit get auf die Instanzvariablen zugreift. Braucht ihr nicht, geht einfacher :)

Ansonsten sehr gut zu lesen, da gute und ausführliche Kommentare, verständliche Benennung der Variablen und der Test ist grün.

VG. Karo (Tutor)

**Comment by Alexander1307** [comment]
Kümmern uns drum. Ist in der IntelliJ IDE gemacht worden. Zur machen wir ein extra repositopry für eclipse. Blos das mit der Struktur habe ich nicht verstanden??

**Comment by Alexander1307** [comment]
Ehm ja das mit den zugriff über get.() habe ich wohl falsch verstanden, dachte wenn ich schon eine Methode schreibe das ich diese dann auch benutze.

**Comment by KaroBee** [comment]
Ja, is ja kein Ding. Die gets werden dann verwendet, wenn jemand von außerhalb des Objekts auf Attribute zugreift: Die VectorTest braucht die :)
Struktur: Hab mal angehängt, wie ein importiertes Projekt aussieht, bei dem ich nur noch den Start-Button drücken muss und es funktioniert, und eures. Könnt ihr das so, wie es ist Committen? Ich kann damit nämlich nichts machen, weil Eclipse es nicht als Eclipse-Projekt erkennt.
![Uploading ist.png . . .]()
![Uploading soll.png . . .]()

**Comment by KaroBee** [comment]
Ich kann es immernoch nicht ausführen - ich habe es in Eclipse eingebunden und die Meldung ist "the selection cannot be launched". Da ist für's Ausprobieren für jeden, der Eclipse benutzt, echt ungünstig. Oder kennt ihr einen Weg, wie ich es ausführen kann und ich mache es nur falsch?
