### ISSUE TITLE
Doppelter Code in Konstruktoren

### ISSUE THREAD

**Issue by KaroBee** [tpe-lecture/group-03#2]
Der leere Konstruktor könnte den anderen Konstruktor mit Vektor(0.0,0.0,0.0) aufrufen. Reduziert die Redundanz von Verweisen auf die Instanzvariablen.

**Comment by Alexander1307** [comment]
???? nix rafing ihr issue

**Comment by KaroBee** [comment]
Es ist eine Code-Dopplung (Redundanz), die nicht notwendig ist. Es gibt bereits einen Konstruktor, der den Instanzvariablen direkt Werte zuweist. Der Leere Konstruktor kann diesen einfach verwenden.

**Comment by Alexander1307** [comment]
Wieso doppelter Code die 2 Konstruktoren waren auch in der Doku drin. Dachte auch das es ein Soll ist daher habe ich das so implementiert..

**Comment by PaulRitterUIB** [comment]
In der Doku steht nichts konkretes. Hab daher mal den Issue umgesetzt.
