### ISSUE TITLE
Exception in addiere() und multiziere()

### ISSUE THREAD

**Issue by TapferesSchneiderlein** [tpe-lecture/group-03#4]
Diese Exception wird nie geworfen, da der else-Zweig bei eurer Bedingung nicht erreicht werden kann, zumindest fällt mir kein Fall ein.
Übersehe ich gerade etwas? Warum habt ihr das so implementiert?

**Comment by Alexander1307** [comment]
public class IllegalArgumentException
extends RuntimeException
Thrown to indicate that a method has been passed an illegal or inappropriate argument.

Und das prüft man mit instanceof. Würde man einen anderen Datentyp übergeben würde es eine exception werfen wenn der compiler einen anderen Datentyp zulassen würde.
Bin mir ziemlich sicher das es so stimmt.
Siehe hier
http://illegalargumentexception.blogspot.de/2009/11/java-how-to-use-illegalargumentexceptio.html
da wird ein String erwartet aber ein int übergeben

**Comment by KaroBee** [comment]
Auch in anderen Gruppen ist ein neues Issue aufgemacht worden, selbst nachdem es mit der o.g. Begründung geschlossen wurde: Stimme Schneiderlein zu, es gibt innerhalb des Programms keinen Fall, der dazu führen könnte, dass dort ein ungültiges Argument übergeben wird. Die Exception-Vewendung ist unnötig.

**Comment by AlexUnderMicrocontRoll** [comment]
Hi,
weil es der Doku so stand die AyJay ;) hinterlassen hat.
---------------------------------------------
multipliziere
public double multipliziere(Vector vektor)
Skalarmultiplikation: Multiplikation des Vektors mit einem Vektor.
Parameters:
vektor - Vektor, mit dem dieser Vector multipliziert werden soll
Returns:
das Ergebnis der Skalar-Multiplikation
Throws:
java.lang.IllegalArgumentException - wenn der Typ von vektor nicht passt
----------------------------------------------------

addiere
public Vector addiere(Vector vektor)
Addiert den gegebenen Vektor zu diesem.
Parameters:
vektor - Vektor, der addiert werden soll
Returns:
das Eregbnis der Addition
Throws:
java.lang.IllegalArgumentException - wenn der Typ von vektor nicht passt
---------------------------

Dachte die Doku ist sowas wie ein Soll, oder habe ich das falsch verstanden?

**Comment by AlexUnderMicrocontRoll** [comment]
sorry die schrift ist iwie gross und fett geworden soll nicht provozierend gemeint sein. kann es nicht ändern.

**Comment by Alexander1307** [comment]
Hi, 
weil es in der Doku so drin stand. Dachte ist eine art Soll.
Oder habe ich das falsch verstanden??

**Comment by PaulRitterUIB** [comment]
![bildschirmfoto 2015-03-26 um 00 58 08](https://cloud.githubusercontent.com/assets/11439673/6838000/76cf21c2-d353-11e4-8e6a-de50310bf609.png)
![bildschirmfoto 2015-03-26 um 00 58 31](https://cloud.githubusercontent.com/assets/11439673/6838001/76cfad72-d353-11e4-9a10-d2f9d03acd82.png)
Das ist der betreffende Dokuausschnitt.
